# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - speckle-v2-preview-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://arupspecklev2prodacr.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_4cad90ecad8440b5aac524055c5fae59 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_30b7688af0df4df883a0e68be50b8636 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: arupspecklev2prodacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4cad90ecad8440b5aac524055c5fae59 }}/arupspecklev2prodacr/arupspecklev2prodacr/preview-service:${{ github.sha }}
          file: ./packages/preview-service/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'p500 - Preview Service'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'speckle-v2-preview-prod'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_9db157e7b79b464dbddd000d57abd0c9 }}
          images: 'arupspecklev2prodacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4cad90ecad8440b5aac524055c5fae59 }}/arupspecklev2prodacr/arupspecklev2prodacr/preview-service:${{ github.sha }}'
